### ISSUE TITLE
Exportação e importação das conversas dos grupos (Alunos e Docentes)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/susi#2]
-  [x] Exportação: Geração de um arquivo .txt
- [x] Converter TXT para CSV
- [x]  Importação para o ElasticSearch

**Comment by ItaloRod** [comment]
O arquivo TXT já foi convertido para o CSV e importado para o ElasticSearch, Gerando também Dashboards com seus principais indicadores.
